---
- name: Update apt
  apt: update_cache=yes
  tags: Base
  
- name: Upgrade the distro
  apt: upgrade=yes
  tags: Base
  
- name: Install System Packages
  apt: pkg={{ item }} state=latest
  tags: Base
  with_items:
    - curl
    - wget
    - vim
    - git
    - python
    - build-essential
    - default-jre
    - software-properties-common
    - chrpath
    - git-core
    - libssl-dev
    - libfontconfig1-dev

