---

- name: Install MySQL
  apt: pkg={{ item }} state=latest update-cache=yes
  with_items:
    - mysql-server
    - python-mysqldb
    - phpmyadmin
  tags: MySQL

- name: Start the MySQL service
  action: service name=mysql state=started
  tags: MySQL

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql.password }} priv=*.*:ALL,GRANT
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  tags: MySQL

- name: Copy .my.cnf file with root password credentials
  template: src=etc/mysql/my.cnf dest=~/.my.cnf owner=root mode=0600
  tags: MySQL

- name: Delete anonymous MySQL server user
  mysql_user: name="" host={{ item }} state="absent"
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  tags: MySQL

- name: Configure MySQL database
  mysql_db: name={{ mysql.database }} state=present
  tags: MySQL

- name: Configure MySQL user
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} host={{ item }} priv=*.*:ALL
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  tags: MySQL

- name: Restart Mysql
  action: service name=mysql state=restarted enabled=yes
  tags: MySQL

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'
  tags: MySQL

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{ mysql.password }}' vtype='password'
  tags: MySQL

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{ mysql.password }}' vtype='password'
  tags: MySQL

- name: debconf for phpmyadmin
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{ mysql.password }}' vtype='password'
  tags: MySQL

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'
  tags: MySQL

- name: install pma
  apt: pkg=phpmyadmin state=present
  tags: MySQL

#- name: configure site
#  file: path=/var/www/phpmyadmin src=/usr/share/phpmyadmin state=link
